version: "3.9"
services:
  python_dev0:
    container_name: django_sample
    build: ./docker/python
    volumes:
      - .:/var/www/html
      - ./templates/static:/var/www/html/templates/static
    working_dir: /var/www/html
    ports:
      - "8000:8000"