version: "3.9"
services:
  python_dev0:
    container_name: python_dev0
    build: ./docker/python
    volumes:
      - .:/var/www/html
      - ./templates/static:/var/www/html/templates/static
    working_dir: /var/www/html
    user: 1001:1001